# Generated by Django 4.1.3 on 2022-11-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('bookname', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('pages', models.CharField(max_length=200)),
            ],
        ),
    ]
