# Generated by Django 4.1.3 on 2022-11-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_delete_book_remove_login_address_remove_login_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='goal1',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='goal2',
        ),
        migrations.AddField(
            model_name='login',
            name='date',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
