# Generated by Django 4.1.3 on 2022-11-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_email_login_goal1_rename_password_login_goal2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
